### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by benhjt** [AtomLinter/linter-csslint#104]
Using Atom 1.7 and linter-csslint 1.3.2 I am receiving the following error

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at file:///C:/Users/***/.atom/packages/linter-csslint/lib/main.coffee:27:29
    at process._tickCallback (node.js:392:9)
```

for all CSS files. Even a simple CSS file containing:

```css
.blah {
	font-size: 14px;
}
```

gives me this error. This happens on typing and during saving.

**Comment by benhjt** [comment]
After looking in the dev tools to try and track down this issue, I now don't receive this error.

**Comment by Arcanemagus** [comment]
There was a bug in Atom v1.7.0 when running processes as Node that caused them to have no output. v1.7.1 fixed this bug. I'm guessing at some point there your install auto-updated to v1.7.1 :wink:.
