### ISSUE TITLE
Error: Process execution timed out

### ISSUE THREAD

**Issue by juanscv** [AtomLinter/linter-csslint#105]
I am editing a .css.liquid file and I get this error every time I save:

```
Error: Process execution timed out
    at %USER%\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:79:18
```

**Comment by emveeoh** [comment]
I also get this error. It happens when I try to open/view very large .CSS files.

**Comment by bronylexx** [comment]
I have the same issue as well. I have enabled the option to disable the timeout but the issue remains.

**Comment by leedorian** [comment]
I also have the time out issue:
`%USER%/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running CSSLint Error: Process execution timed out(…)(anonymous function) @ %USER%/.atom/packages/linter/lib/linter-registry.js:159
%USER%/.atom/packages/linter-csslint/node_modules/sb-exec/lib/index.js:59 [exec] Process exited with no-zero code, stdout:  {"messages":[{"type":"warning","line":3,"col":15,"message":"Use of `

**Comment by bronylexx** [comment]
I have fixed my issues by switching to [AtomLinter](https://atomlinter.github.io). My suggestion is based on #153 and #162 where Arcanemagus advised that development on this package is dead.
