### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by rakkarage** [AtomLinter/linter-csslint#11]
i am using windows

the default path

    csslintExecutablePath: path.join __dirname, '..', 'node_modules', '.bin'

points to a cmd file which is not a node executable i guess

    isNodeExecutable: yes

if i remove this line (which i see you just added) (but i am trying this for first time anyway) then it works

thanks

**Comment by Braintelligence** [comment]
Thank you for this... I thought I was going insane.

**Comment by Arcanemagus** [comment]
Just to tie things together, this is fixed in https://github.com/AtomLinter/linter-csslint/pull/14.

**Comment by steelbrain** [comment]
Merging into #29
