### ISSUE TITLE
css linter not working

### ISSUE THREAD

**Issue by zepoland** [AtomLinter/linter-csslint#115]
Hi 

linter-csslint 1.3.2 not working at all for me. Not detecting any errors. Could you help?

For your reference I'm using it with:
OS X 10.11.5
Atom 1.8.0

Other linter packages installed:
Linter 1.11.11
linter-htmlhint (this works fine)
linter-jshint

**Comment by Arcanemagus** [comment]
I would _highly_ recommend you check out [linter-stylelint](https://atom.io/packages/linter-stylelint) as it is a far better written linter.

If you do still need this working, the first step is to check whether it is even being triggered by opening Atom's Developer Tools and putting a breakpoint [here](https://github.com/AtomLinter/linter-csslint/blob/v1.3.2/lib/main.coffee#L15), if that is being hit, then place one [here](https://github.com/AtomLinter/linter-csslint/blob/v1.3.2/lib/main.coffee#L27) and see what `output` contains.

**Comment by zepoland** [comment]
Thanks a lot for your answer Arcanemagus.

I´m still too green with coding to try the solution you suggest for CSS Linter. However, I have installed linter-stylelint and it's working OK with the only exception it doesn't pick some errors (e.g. if there's an error in the name of a property). Not sure if it´s supposed to do that as well.

In any case thanks again for your help!

**Comment by Arcanemagus** [comment]
Make sure you check the "Use Standard" option in the settings, or provide a [configuration](http://stylelint.io/user-guide/configuration/) of your own for your project, it should catch _many_ things like that 😉.

**Comment by zepoland** [comment]
Thanks again Arcanemagus. All working great now. 
Cheers!
