### ISSUE TITLE
[Feature suggestion] Option to disable only warnings

### ISSUE THREAD

**Issue by joubertredrat** [AtomLinter/linter-csslint#137]
Hi guys,

This plugin is very nice, but I think that this can have a option to disable warnings, then I will display for me only errors. What you think?

Thanks.

**Comment by Arcanemagus** [comment]
You should be able to fix this yourself by creating a `.csslintrc` file, see [here](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files).
