### ISSUE TITLE
Problem with Linter Error.   How can I suppress the Linter error?

### ISSUE THREAD

**Issue by JeffGreenlee42** [AtomLinter/linter-csslint#152]
Hi,   I think the below CSS code is legitimate... but Linter is not having it!    I am attempting to add an a backslash character  using the CSS pseudo "after" tag  into a list item.   I have to use a "\\" because a single backslash will definitely not work! 

`
.meta li:after {
	content: "\\";
	padding: 0 2px;
	color: #999;
}
`

  This CSS  has the affect I am after,  however Linter produces an error message:  

> ERROR:  Unexpected token '"\\\\";'  at line yada yada yada... 

Is this an error I can supress in AtomLinter or Linter-csslint?

**Comment by Arcanemagus** [comment]
The error is coming from CSSLint, you would need to file an issue [over there](https://github.com/CSSLint/csslint/issues/new), however I would _highly_ recommend looking into moving to [stylelint](http://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)) as it is actively maintained and built in a modern fashion, both qualities that CSSLint lacks.
