### ISSUE TITLE
Linter-csslint does not work after updating Atom. 

### ISSUE THREAD

**Issue by tkm-mur** [AtomLinter/linter-csslint#156]
Linter-csslint does not work after updating Atom. However, linter-htmlhint and linter-jshint will work. Please tell me how to solve it.

Atom ver 1.12.4
Mac os 10.12

**Comment by Arcanemagus** [comment]
I've been looking into this over in https://github.com/AtomLinter/linter-csslint/pull/155, unfortunately the current path forward is either fixing whatever is in [atomlinter/csslint](https://github.com/AtomLinter/csslint) that is breaking things, or preferrably updating that to the current state of [csslint](https://github.com/CSSLint/csslint), but with https://github.com/CSSLint/csslint/pull/605 merged in so we can still use it. If the second path is chosen, then this package would need updating.

On the other hand, [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) / [stylelint](http://stylelint.io/) is a _much_ better CSS (and more!) linter, so I would highly recommend you look into switching to that. I don't personally use CSSLint myself, so this package is a rather low priority for me.

**Comment by tkmmur** [comment]
Now, it seems that it works normally after installing linter-stylelint / stylelint, so I will use it here. Thank you.

**Comment by gitanupam** [comment]
Wanted to add that linter-csslint still does not work (i.e does nothing) on Atom 1.14.1 and Mac OS X El Captain. Trying out linter-stylelint.

**Comment by Arcanemagus** [comment]
Fixed by @ericandrewlewis over in https://github.com/AtomLinter/csslint/pull/8, and brought into this package in #155.
