### ISSUE TITLE
.csslintrc not used

### ISSUE THREAD

**Issue by tomsotte** [AtomLinter/linter-csslint#158]
EDIT: I've seen in the issues here that's it's not implemented.

I've placed in the root of my project a file named ".csslintrc" and tried some rules but none of those worked.
I've tried to restart the plugin and even Atom but nothing worked, the rules I've set are ignored.

I believe the format is in JSON.
Example of what a tried:
```json
{
	"adjoining-classes": true,
	"box-model": false,
	"box-sizing": false,
	"bulletproof-font-face": false,
	"compatible-vendor-prefixes": false,
	"display-property-grouping": false,
	"duplicate-background-images": false,
	"duplicate-properties": false,
	"empty-rules": false,
	"fallback-colors": false,
	"floats": false,
	"font-faces": false,
	"font-sizes": false,
	"gradients": false,
	"ids": false,
	"import": false,
	"important": false,
	"known-properties": false,
	"non-link-hover": false,
	"outline-none": false,
	"overqualified-elements": true,
	"qualified-headings": false,
	"regex-selectors": false,
	"shorthand": false,
	"star-property-hack": false,
	"text-indent": false,
	"underscore-property-hack": false,
	"vendor-prefix": false,
	"unique-headings": false,
	"universal-selector": false,
	"unqualified-attributes": false,
	"zero-units": false
}
```

**Comment by Arcanemagus** [comment]
Actually, it _should_ be working, #140 is about overriding the automatic detection and telling it explicitly where the config is located.

**Comment by tommasosotte** [comment]
Interesting.
What could I try to make it work?
I really don't like stylelint for the fact that it has way to much configuration options.

**Comment by Arcanemagus** [comment]
Does `csslint foo.js` work when ran from the project root?

**Comment by tommasosotte** [comment]
I'm sorry for the late response. Here's what i get
`
$ csslint style.clean.css
adjoining-classes is not a valid option. Exiting...
`

The .csslintrc is the above.
I've just checked and it is an existing rule apparently: https://github.com/CSSLint/csslint/search?utf8=%E2%9C%93&q=adjoining-classes&type=Code

**Comment by Arcanemagus** [comment]
That output means that it _is_ using the `.csslintrc`, however your `.csslintrc` has an invalid option that `csslint` doesn't understand.

**Comment by brendanmckeown** [comment]
I am also getting the error "adjoining-classes is not a valid option. Exiting..." when trying to run `csslint` on any file.

@Arcanemagus - `adjoining-classes` is definitely one of the valid rules shown in the output of `csslint --list-rules`.

**Comment by brendanmckeown** [comment]
The issue is that the supported format of the `.csslintrc` has changed from JSON to:
```
--errors=adjoining-classes
--warnings=import,text-indent
--ignore=box-model
```

**Comment by Arcanemagus** [comment]
@brendanmckeown As far as I know CSSLint has only ever supported that format, that's what has been [documented](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files) at least.

**Comment by brandly** [comment]
@Arcanemagus that link you provided has [an example `.csslintrc` that is JSON...](https://github.com/ebednarz/csslintrc/blob/master/.csslintrc)

**Comment by Arcanemagus** [comment]
@brandly Then go tell `csslint` they have terrible documentation? 😛
