### ISSUE TITLE
linter-csslint not working in atom

### ISSUE THREAD

**Issue by LiquidFlame** [AtomLinter/linter-csslint#16]
Hello,

I'm new to Atom, so sorry if this is something obvious, but I did some searching and couldn't find anything. I just installed Atom, and the only other packages I've installed are linter, linter-javac, linter-jshint, and linter-csslint. The other linter packages work fine, but the csslint is unresponsive. I'm not sure if I need to do any more configuration, but I installed it like the rest of the packages. I went into command line and typed "apm install linter-csslint", and then opened Atom, and I could see the packaged installed.

I then went to CSS Lint, to find a an example and created a new file "testcss.css" and entered the following:

>.foo h1 {
>font-size: 110%
>}
>
>.test {
>
>}

When I move the cursor around the lines, I don't get any kind of error message from the csslint. I'm using a Windows 7 machine. Any help would be appreciated.

Thanks.

**Comment by Arcanemagus** [comment]
Can you check and see if the fix in https://github.com/AtomLinter/linter-csslint/pull/14 gets this working for you? It is highly likely that that is your issue.

**Comment by steelbrain** [comment]
Merging into #29
