### ISSUE TITLE
Is there anyway to edit linter rules.

### ISSUE THREAD

**Issue by JeffCleverley** [AtomLinter/linter-csslint#160]
My OCD is screaming... I would like to use ID as a selector on occassion... I don't care what this is saying...

IS there anyway to edit the rules so I can ignore this warning more easily>

**Comment by Arcanemagus** [comment]
You should be able to [configure CSSLint](https://github.com/CSSLint/csslint/wiki/Command-line-interface#configuration-files) to accomplish this, I would _highly_ recommend moving to [stylelint](https://stylelint.io/) though as csslint has been virtually dead for almost 2 years now.

**Comment by JeffCleverley** [comment]
@Arcanemagus 

Funnily enough, after reading someone else's comments yesterday I have already migrated to styleling.
