### ISSUE TITLE
Update CSSLint to use newer @ rules such as @supports

### ISSUE THREAD

**Issue by bvdputte** [AtomLinter/linter-csslint#162]
I am using the latest linter-csslint, but I keep getting errors or warnings on recent css properties such as

- @supports
- contain

How can I solve this?

Thx

**Comment by Arcanemagus** [comment]
First of all, does `csslint` itself even support it? If so, then either https://github.com/CSSLint/csslint/pull/605 needs to be merged so we can start using `csslint` itself again, or [AtomLinter/csslint](https://github.com/AtomLinter/csslint) needs to be updated to the current state of `csslint`. I have zero interest in maintaining this beyond making sure it still works at all, so this project is currently without a maintainer.

It's highly unlikely that `csslint` supports any of that though as development has essentially been dead there for quite a while. I would recommend you move on to [stylelint.io](https://stylelint.io/) as it is a modern CSS linter based on PostCSS. [linter-stylelint](https://github.com/AtomLinter/linter-stylelint) is available for integration in Atom 😉.

**Comment by bvdputte** [comment]
Thanks for the reply!

I haven't checked if csslint doesn't support it, sorry 🙈.
Thanks for the tip about stylelint.io, I'll check it out. 👍

**Comment by Arcanemagus** [comment]
Marking this as closed, if it isn't already supported, then support would need to be done over in CSSLint as this project is just a wrapper around that.
