### ISSUE TITLE
Error running CSSLint Error: 'node' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Modelsson** [AtomLinter/linter-csslint#172]
Hello,

Linter CSS keeps giving me this error which I cannot figure out how to correct. Can any one help me?

[-1507638789422.log](https://github.com/AtomLinter/linter-csslint/files/1371851/-1507638789422.log)

**Comment by Modelsson** [comment]
I would like to add that since I uninstalled it it no longer force-closes Atom.

**Comment by Arcanemagus** [comment]
My guess is that this is yet another instance of how badly written CSSLint is, can you try installing Node.js on your system?

**Comment by Modelsson** [comment]
I installed the current (8.6.0.) release, reinstalled linter-CSSlint, and it seems to be working. Wow! Can you just quickly explain what I installed and why is it working now?

**Comment by Arcanemagus** [comment]
As of https://github.com/AtomLinter/linter-csslint/pull/170 this package is running `csslint` as it's own program, instead of through Atom's environment. This means you need to have Node.js installed on your system to be able to execute it.

(I was confusing this and `bootlint` earlier, which requires `node` to be installed on the system even when ran from the `node` built into Atom.)

Glad to hear that's working for you!

**Comment by Modelsson** [comment]
Thank you for your help!

**Comment by davupls** [comment]
> My guess is that this is yet another instance of how badly written CSSLint is, can you try installing Node.js on your system?

Yup truns out you were right.

**Comment by DawnRahul** [comment]
Thank you, It worked successfully.

**Comment by claudiofons** [comment]
Thank you. work for me to.

**Comment by parandhamgoud** [comment]
linter-csslint:: Error while running CSSLint!

'"node"' is not recognized as an internal or external command,
operable program or batch file

**Comment by SJKhayat** [comment]
Thx!

**Comment by kostism3** [comment]
works fine.thanks

**Comment by jambwa** [comment]
linter-csslint:: Error while running CSSLint!

'"node"' is not recognized as an internal or external command,
operable program or batch file  

how do you solve this

**Comment by GAUTAM6102** [comment]
linter-csslint:: Error while running CSSLint!

'"node"' is not recognized as an internal or external command,
operable program or batch file

how do you solve this

**Comment by GAUTAM6102** [comment]
node.js is installed but still this error is not going away
