### ISSUE TITLE
Error when editing CSS files that begin with a comment

### ISSUE THREAD

**Issue by mbacon40** [AtomLinter/linter-csslint#176]
I am attempting to use CSSLint with atom and am running into an issue where CSSLint does not work when editing some CSS files. The issue seems to be with opening files from a project where the CSS file begins with a comment.

I see this error in the linter:
> Invalid response received from CSSLint, check your console for more details

In the console:
> IntersectionObserver.observe(target): target element is not a descendant of root.

I have experimented with removing the comment from the beginning of the file and saving but it does not fix the issue. If I open a simple CSS file from my desktop that does not begin with a comment, then CSSLint works fine.

**Comment by Arcanemagus** [comment]
Hmmm that console message is unrelated (It comes from Atom core). There _should_ have been an error message printed there. I'll try to reproduce...

**Comment by Keesromkes** [comment]
I can confirm this issue as well, my css starts with /*, and throws that same error (couldn't find anything in the console by the way...)

**Comment by Arcanemagus** [comment]
What happens if you run `csslint` on the file in the CLI?

**Comment by Keesromkes** [comment]
Looks like it works again (?)

**Comment by mbacon40** [comment]
This did not work for me. 

I was able to make CSSLint work on a newly created file that began with a comment. This worked great for a while but eventually, the same error eventually came up. I am not sure if this is because the file length got long, or if it was due to closing the file/atom and reopening it.

**Comment by Arcanemagus** [comment]
If one of you can save the file at the _exact_ moment you see that, and if it keeps giving you the error every time you save could you share it with me so I can reproduce this?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response. If anyone is able to get a file in a state the reliably reproduces this please post it here or send it to me so I can track down where the problem is.

**Comment by seriousm4x** [comment]
I'm having the exact same issue as @mbacon40.

Versions I'm running:
macOS 10.13.3
Homebrew 1.5.4
atom 1.24.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
csslint v1.0.4

How to reproduce:
I installed node/npm via brew with `npm install -g csslint`. Then I changed the executable path to the location where brew installs it to (`/usr/local/bin/csslint`). And thats it. I'm testing it with [this](https://github.com/seriousm4x/gogsBase16/blob/master/gogsBase16.css) css file.

Error in editor:
<img width="1300" alt="error below file" src="https://user-images.githubusercontent.com/23456686/36248325-6176dfb0-1237-11e8-8b4d-ab465959b7b4.png">

Console error:
<img width="553" alt="console" src="https://user-images.githubusercontent.com/23456686/36248253-20d5f3b0-1237-11e8-9a95-8286fd7db1c3.png">

Running csslint with that file in my terminal works as expected.

@Arcanemagus tell me what details you need
