### ISSUE TITLE
smacss sorting suppurt

### ISSUE THREAD

**Issue by dzhytomyrsky** [AtomLinter/linter-csslint#178]
Is it possible to set smacss sorting as css rule for this linter?

And is it possible to set my own csslint rules?

**Comment by Arcanemagus** [comment]
`csslint` development is essentially dead, you can _try_ filing an issue [over there](https://github.com/CSSLint/csslint) about this, but I would _highly_ suggest you move on to [stylelint](https://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)).

To answer your questions:
No and no.
