### ISSUE TITLE
Expected RBRACE error

### ISSUE THREAD

**Issue by JasperKuiper** [AtomLinter/linter-csslint#182]
Using var's in CSS produces error by CSSLint, although CSS responds as expected. Error should not be shown....

![2017-12-28](https://user-images.githubusercontent.com/17339742/34409708-ce80eaf2-ebcb-11e7-9008-2b4c0f229bb0.png)
![2017-12-28 2](https://user-images.githubusercontent.com/17339742/34409709-ce96926c-ebcb-11e7-912f-7fb710cf2a6c.png)

**Comment by Arcanemagus** [comment]
You'll need to file this on [csslint](https://github.com/CSSLint/csslint) as this is just a wrapper around that.

Or alternatively you can do yourself a favor and move to the ESLint of CSS: [stylelint](https://stylelint.io/) ([linter-stylelint](https://atom.io/packages/linter-stylelint)).
