### ISSUE TITLE
IntersectionObserver.observe(target): target element is not a descendant of root. (Mac 10.11.6)

### ISSUE THREAD

**Issue by ryanchristie** [AtomLinter/linter-csslint#186]
Atom: 1.21.3 x64
Electron: 1.6.15
OS: Mac 10.11.6
Thrown From: linter-csslint package 2.0.0

Developer console:

`IntersectionObserver.observe(target): target element is not a descendant of root.`
`EACCES: permission denied, symLink '/Applications/Atom.api/Contents/Resources/app/atom.sh' -> '/usr/local/bin/atom'`
`EACCES: permission denied, symLink '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm' -> '/usr/local/bin/apm'`

**Comment by ryanchristie** [comment]
process.versions:

ares: 1.10.1-DEV
atom-shell: 1.6.15
chrome: 56.0.2924.87
electron: 1.6.15
http_parser: 2.7.0
modules: 53
node: 7.4.0
openssl: 1.0.2j
uv: 1.10.1
v8: 5.6.326.50
zlib: 1.2.8

**Comment by ryanchristie** [comment]
Here is the file throwing the error.

[css.txt](https://github.com/AtomLinter/linter-csslint/files/1670762/css.txt)

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
