### ISSUE TITLE
Invalid response received from CSSLint, check console for more details.

### ISSUE THREAD

**Issue by brianlpham21** [AtomLinter/linter-csslint#189]
Receiving this error after npm install and install on Atom Editor. 

Executable path set to `/usr/local/bin/csslint`

**Comment by HackerGaucho** [comment]
same problem in "linter-csslint v2.0.6"  with "atom v1.57.0".

i found the problema after add a ".csslintrc" file with [this code](https://github.com/ebednarz/csslintrc).
