### ISSUE TITLE
Invalid response received from CSS Lint

### ISSUE THREAD

**Issue by er777** [AtomLinter/linter-csslint#192]
Latest version of Atom - OSX.

[style.css.zip](https://github.com/AtomLinter/linter-csslint/files/2043270/style.css.zip)

**Comment by Arcanemagus** [comment]
CSSLint is a rather buggy linter, it often returns points that don't exist in the document.

Please verify that running `csslint` on the file reports points that are all within the document itself, if you think that it is then I can investigate further, otherwise file a bug on CSSLint 😉.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response and extreme probability that this is a CSSLint bug.
