### ISSUE TITLE
Linter cannot detect ';' sign absence after CSS declaration

### ISSUE THREAD

**Issue by yialo** [AtomLinter/linter-csslint#193]
Atom: 1.27.1 x64
OS: Windows 7 SP1
Thrown From: linter-csslint package 2.0.1

CSS linter cannot detect ';' sign absence after any CSS declaration. Fix this please.

**Comment by Arcanemagus** [comment]
This is just a wrapper around [csslint](https://github.com/CSSLint/csslint), you'll need to either configure that to tell you this, or use a better linter such as [stylelint](https://stylelint.io/).
