### ISSUE TITLE
After Install the package , when i open CSS files , every time alarm this error

### ISSUE THREAD

**Issue by ViGilanteAF** [AtomLinter/linter-csslint#199]
First of all i used MacOS HighSierra.
i tryed uninstall and reinstall this package i can't findout solution.
The Error Code is this 
```
linter-csslint:: Error while running CSSLint!
env: node: No such file or directory
```

**Comment by Arcanemagus** [comment]
This package is just a wrapper around running `csslint` in your terminal, as such you need to have Node.js installed on your system for it to work.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response from the original filer.
