### ISSUE TITLE
linter-csslint:: Error while running CSSLint! "node" isn't reconoced as a command intern or extern

### ISSUE THREAD

**Issue by aabaenar** [AtomLinter/linter-csslint#205]
I am to try install linter-csslint, and i installed node.js, the "node" command is in global PATH, i tested that. But appears this message .
![imagen](https://user-images.githubusercontent.com/24502193/46641786-14f56100-cb39-11e8-85bf-41c8ce64ad8f.png)
My atom is in spanish, the translate is "node is not recognized as an internal or external command,
Program or batch file executable."

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
