### ISSUE TITLE
linter-csslint:: Error while running CSSLint!

### ISSUE THREAD

**Issue by robertagp** [AtomLinter/linter-csslint#206]
When opening atom I keep getting an error from CSSLint

linter-csslint:: Error while running CSSLint!
env: node: No such file or directory

Would you be able to help, please? 

Thanks!

<img width="655" alt="screen shot 2018-10-23 at 8 22 18 am" src="https://user-images.githubusercontent.com/44391027/47339845-c4cfe000-d69c-11e8-92e0-985d739e3153.png">

**Comment by robertagp** [comment]
Hi, I installed node.js via homebrew following these steps:

https://blog.teamtreehouse.com/install-node-js-npm-mac


and now I get this error when opening atom:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1000382cf node::Abort() [/usr/local/bin/node]
 2: 0x1000384a0 node::FatalTryCatch::~FatalTryCatch() [/usr/local/bin/node]
 3: 0x10016cd1f v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10016ccc0 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10041fdb8 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/bin/node]
 6: 0x100421987 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 7: 0x10041f0a0 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10041de9e v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x10041e0e9 v8::internal::Heap::CollectAllAvailableGarbage(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
10: 0x100426741 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x100406a0b v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x1004082e7 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
13: 0x10065c7d2 v8::internal::IncrementalStringBuilder::Extend() [/usr/local/bin/node]
14: 0x1004b4d6d v8::internal::JsonStringifier::SerializeString(v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
15: 0x1004b7dfc v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
16: 0x1004b6eec v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
17: 0x1004b8d4c v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
18: 0x1004b6eec v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
19: 0x1004b3503 v8::internal::JsonStringifier::Stringify(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/usr/local/bin/node]
20: 0x1001fc8ad v8::internal::Builtin_Impl_JsonStringify(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
21: 0x3a0f5875bf9d


Any idea what I can do? :(

**Comment by Arcanemagus** [comment]
Looks like CSSLint ran out of memory while attempting to build the result report. Besides fixing the errors I'm not sure what else you can do here but it doesn't appear to be anything related to this package so I'm going to close the issue. Feel free to comment further if you are still seeing this and need help diagnosing it.

**Comment by shulongjin** [comment]
> 打开atom时我不断收到CSSLint的错误
> 
> linter-csslint ::运行CSSLint时出错！
> env：node：没有这样的文件或目录
> 
> 你能帮忙吗？
> 
> 谢谢！
> 
> <img alt="屏幕截图2018-10-23于8月22日18点18分" width="655" src="https://user-images.githubusercontent.com/44391027/47339845-c4cfe000-d69c-11e8-92e0-985d739e3153.png">

最后解决问题了吗？
