### ISSUE TITLE
Please add a setting to disable HTML linting

### ISSUE THREAD

**Issue by stephaniehobson** [AtomLinter/linter-csslint#207]
Our team uses jinja, a django templating engine which creates files with a .html extension.

These files should not be linted by CSS Lint but I do not see a way to disable the HTML linting or exclude the .html file type from being linted.

Thank you :)

**Comment by Arcanemagus** [comment]
I'm actually not sure why it has been enabled in the first place here, `csslint` doesn't appear to automatically strip the CSS out of HTML pages based on their README.
