### ISSUE TITLE
Why am i getting an error for html code?

### ISSUE THREAD

**Issue by Guy6767** [AtomLinter/linter-csslint#209]
<img width="960" alt="2018-12-03" src="https://user-images.githubusercontent.com/42813496/49391194-a6e1aa80-f733-11e8-8433-003277b003c1.png">

I am getting this error from csslinter without even writing one line of css.
What am i doing wrong?

**Comment by ChilobeMwanza** [comment]
same!

**Comment by Arcanemagus** [comment]
Duplicate of #207
