### ISSUE TITLE
Error while running CSS-Lint

### ISSUE THREAD

**Issue by digbydesign** [AtomLinter/linter-csslint#212]
Every time I save the css document it throws the error: "'node' is not recognized as an internal or external command, operable program or batch file."
Is there something I can do in the settings to amend this?

**Comment by Arcanemagus** [comment]
You need to have [Node.js](https://nodejs.org/en/) installed on your machine in order to run `csslint`. This is just a wrapper around running that that gets the output into a format usable in Atom's ecosystem.
