### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by projectssome** [AtomLinter/linter-csslint#214]
I'm getting the following message: `Invalid response received from CSSLint, check your console for more details.`, and when checking the console there's nothing regarding csslint, as you can see below. Any idea on what's wrong?

```
"csslint": "^1.0.5",
"eslint": "^5.11.1",
"eslint-config-airbnb": "^17.1.0",
"eslint-plugin-import": "^2.14.0",
"eslint-plugin-jsx-a11y": "^6.1.2",
"eslint-plugin-react": "^7.12.0",
"htmlhint": "^0.10.1"
```

![screen shot 2019-01-01 at 2 59 30 pm](https://user-images.githubusercontent.com/44626533/50574763-10f27b80-0dd6-11e9-947e-6e991ac20d92.png)

**Comment by jtomeck** [comment]
![screen shot 2019-02-06 at 1 40 59 pm](https://user-images.githubusercontent.com/1560779/52365415-69d8b380-2a15-11e9-8dcb-d01f374229f5.png)

I'm getting this same error, but this is what I see in my console. @Arcanemagus Maybe this will help fix the issue?

**Comment by Arcanemagus** [comment]
Ah, your issue is that a run was cancelled by a later run, and the `null` coming back from `exec` isn't being handled correctly.

**Comment by nylki** [comment]
not sure if it is indeed resolved. I still get the same error in 2.0.5, restarted Atom after package update.

**Comment by Arcanemagus** [comment]
Please file a _new_ issue then, including any details from the console. Thanks!
