### ISSUE TITLE
The fr units for grids is not supported.

### ISSUE THREAD

**Issue by BootsElectric** [AtomLinter/linter-csslint#229]
When creating a grid structure using fr units for spacing the linter reports an `Unexpected token '1fr'` .

**Comment by Arcanemagus** [comment]
This is just a wrapper around `csslint`, you'll need to file this there.

Note that `csslint` hasn't received any real changes in several years, it would _highly_ recommend switching to [stylelint](https://stylelint.io/) (and [linter-stylelint](https://atom.io/packages/linter-stylelint)).
