### ISSUE TITLE
Inline Error not showing

### ISSUE THREAD

**Issue by alybiblawy** [AtomLinter/linter-csslint#249]
Ive recently installed linter but i cant seem to get the little red dots to display any errors within my code, also realistically i do not think any errors are being recognized

**Comment by Arcanemagus** [comment]
* Do you have `csslint` installed on your system?
* Is `csslint` working correctly?
* Do you have a consumer for this provider installed? (`linter`, `atom-ide-ui`)
* Is the consumer enabled?
* Are you seeing any errors in the console?

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
