### ISSUE TITLE
Invalid response received from CSSLint, check your console for more details.

### ISSUE THREAD

**Issue by vizzale** [AtomLinter/linter-csslint#250]
Hi @Arcanemagus ,
I been using Atom for 1 year and a half, I do not use many packages and among my irreplaceable Linters is one of them. I used Linter without any problems until last year (2018), then I re-opened Atom in January, without making any changes, other than simply updating, and now whatever I do is not identified any problems in the code even if the problems are there.

Maybe it can help you know that:
- I have correctly installed linter-csslint (2.0.6) from the settings from "Atom > Settings > Install";
- I installed linter (2.3.0) but not atom-ide-ui;
- linter is active;
- this is the error that occurs in the console: "Invalid response received from CSSLint, check your console for more details."

Without opening two other issues I would also like to add here that neither linter-stylelint (4.4.7) and linter-htmlhint (1.6.1) show signs of life. In this case, no error messages appear.

Finally I use the version 1.37.0 of Atom.

**Comment by Arcanemagus** [comment]
Do you have `csslint` installed and working on your system?

The `csslint` project itself is dead, and nobody stepped up to maintain a fork here so this project has been forced to become a wrapper around executing that separately instead of calling it directly. This means that you _must_ be able to run `csslint` on the files before you can attempt to use it within Atom.

----

> I would also like to add here that neither linter-stylelint (4.4.7) and linter-htmlhint (1.6.1) show signs of life. In this case, no error messages appear.

"not working" doesn't give much to go on, you'll need to provide more information than that.

What does the `Linter: Debug` command show when ran on a file you are expecting results for?

**Comment by vizzale** [comment]
I'm not an expert user, so I can only tell you that CSSLint is installed.

For the info, here's to you:

**Linter Debug Info**
Platform: darwin
Atom Version: 1.37.0
Linter Version: 2.3.0
Opened file is ignored: No
Matching Linter Providers: 
  - CSSLint
  - stylelint
Disabled Linter Providers: 
Standard Linter Providers: 
  - CSSLint
  - htmlhint
  - JSHint
  - stylelint
Indie Linter Providers: 
UI Providers: 
  - Linter
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.css

**Comment by Arcanemagus** [comment]
You have `linter-csslint` (this package) installed, you **also** need `csslint` itself installed if you want this provider to work.

----

For `linter-stylelint` have you created a [`stylelint` configuration](https://stylelint.io/user-guide/configuration/)?

**Comment by vizzale** [comment]
For linter-csslint: yes I have installed also CSSLint (https://github.com/tcarlsen/atom-csslint).
Maybe the problem is here?
![image](https://user-images.githubusercontent.com/37701762/58584454-97f93200-8256-11e9-8537-0d99e7e1a7eb.png)
_____________________________________________________________________________________________________
For linter-stylelint: no I didn't create it, is it very complex to do it?
_____________________________________________________________________________________________________
For linter-htmlhint : do you have any ideas for this? a few months ago (along with linter-csslint) it worked perfectly.

**Comment by Arcanemagus** [comment]
You need the actual `csslint` program installed on your computer, **not** an Atom package. You can do this with `npm install --global csslint`.

----

I linked you the documentation on it.

----

The provider is listed as installed, beyond that I don't know since all you have provided is that it "isn't working".

**Comment by vizzale** [comment]
Hi @Arcanemagus,
I apologize if I was late in replying, but before adding anything else I preferred to do all the necessary tests and clarify the situation a little. 

I managed to solve the problem I had with _linter-htmlhint_ so I will only use this issue to talk about _linter-csslint_ as I should have done from the beginning. For _linter-stylelint_ instead I will open a specific issue with my doubts.

First of all, I ask you: if I decide to use linter-stylelint does it make sense to also use linter-csslint, based on your experience, since it is no longer supported?
As you indicated I have however installed CSSLint through the command: `npm install --global csslint`; then the system asked me if I wanted to update npm and ran the command `npm i -g npm`.
Now I try to open a .css file but the console gives me always gives me the usual mistake:
```
Severity: Error
Provider: CSSLint
Description: Invalid response received from CSSLint, check your console for more details.
```

Meanwhile, I thank you for your help and patience.

**Comment by Arcanemagus** [comment]
It _should_ be printing the "invalid" output from CSSLint in the console, without that I can't really say anything else.

> If I decide to use linter-stylelint does it make sense to also use linter-csslint, based on your experience, since it is no longer supported?

I don't personally use either provider much as I don't do very much front end work, however from everything I've seen you shouldn't need CSSLint if you are using stylelint.

**Comment by vizzale** [comment]
Thanks for your answers.
In the end I managed to make CSSLint work too by installing it globally but restarting the notebook.
I will use Stylelint because it seems complete and offers the possibility of being extended. I have some questions about Stylelint but it doesn't seem like the right question to ask. In fact I really wanted to ask you if I can use the issues to even ask simple questions.

Thanks a lot.

**Comment by Arcanemagus** [comment]
> In the end I managed to make CSSLint work too by installing it globally

Glad to hear it, I'll go ahead and mark this issue closed then.

> In fact I really wanted to ask you if I can use the issues to even ask simple questions.

I generally would prefer things like that to be in the `#linter` channel in [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) as things are far more visible in there. Issues can work, but responses may be sporadic.
