### ISSUE TITLE
linter-csslint:: Error while running CSSLint!

### ISSUE THREAD

**Issue by Kusine** [AtomLinter/linter-csslint#276]
The following error message occurs when I save a **CSS** file:

```
linter-csslint:: Error while running CSSLint!
env: node: No such file or directory
```

I have installed and uninstalled **linter-csslint** and I believe **Linter** is properly installed. I did not have this issue in the past.

Running Atom with MacOS 10.15.1.

**Comment by Arcanemagus** [comment]
You need to install Node.js on your system to run `csslint`.
