### ISSUE TITLE
Appears to be broken, now that isNodeExecutable is false

### ISSUE THREAD

**Issue by AlexanderOMara** [AtomLinter/linter-csslint#28]
I just noticed this linter does not appear to be working with the latest update. I think I've tracked down the issue to [this commit](https://github.com/AtomLinter/linter-csslint/commit/9e2a516a0912712079ef72b2515f4d2639348f97) and [pull request](https://github.com/AtomLinter/linter-csslint/pull/14).

On OS X, it seems that having `isNodeExecutable` not be true prevents it from running. If I set the value back to true via the debugger, it starts to work again.

![debugger](https://i.imgur.com/HX37Kry.png)

Some more information on where it fails:

![no such file](https://i.imgur.com/TBN6BWy.png)

I believe this is because the node binary is not in the path when executed through BufferedProcess.

**Comment by AlexanderOMara** [comment]
This issue appears to be related to this issue on the parent linter plugin:

https://github.com/AtomLinter/Linter/issues/726

This workaround make it work again:

https://github.com/AtomLinter/Linter/issues/726#issuecomment-120666636

**Comment by steelbrain** [comment]
Will be fixed by of #29
