### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ilanbiala** [AtomLinter/linter-csslint#3]
Please add a Changelog.md file for people to see what changed.

**Comment by ilanbiala** [comment]
@dmnd status? Is this going to happen, or should I just close?

**Comment by dmnd** [comment]
PRs welcome. I don't see any harm in leaving this open until it gets done. Same goes for the other 2 times you wrote this comment in other repos.

**Comment by steelbrain** [comment]
Closing as oudated

**Comment by ilanbiala** [comment]
@steelbrain what do you mean outdated? It hasn't been done yet...

**Comment by steelbrain** [comment]
@ilanbiala I know, and We would love to review a PR for that, but We (okay, me) are super-busy these days and I haven't seen much activity so the only way I see this getting implemented is by a community member or someone else.

**Comment by ilanbiala** [comment]
@steelbrain that's fine, but closing the issue means community members won't see it....so how would they make a PR for it?

**Comment by ilanbiala** [comment]
Why don't you guys use https://github.com/rafinskipg/git-changelog or https://github.com/ajoslin/conventional-changelog which does it automatically?

**Comment by steelbrain** [comment]
Fine
