### ISSUE TITLE
Can't install package, other instalations are successful

### ISSUE THREAD

**Issue by emcek** [AtomLinter/linter-csslint#36]
C:\Users\emc>apm upgrade
Package Updates Available (2)
├── git-plus 5.2.3 -> 5.2.4
└── linter-csslint 0.0.14 -> 1.0.0

Would you like to install these updates? (yes) yes

Installing git-plus@5.2.4 to C:\Users\emc\.atom\packages done
Installing linter-csslint@1.0.0 to C:\Users\emc\.atom\packages failed

npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/AtomLinter/csslint) git://github.com/msysgit/msysgit
npm ERR! git clone git://github.com/AtomLinter/csslint Cloning into bare repository 'C:\Users\emc\.atom\.apm\_git-remotes\git-github-com-AtomLinter-csslint-da61e1bd'...
npm ERR! git clone git://github.com/AtomLinter/csslint fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/AtomLinter/csslint github.com[0: 192.30.252.128]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\emc\\AppData\\Local\\atom\\app-1.0.4\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\emc\\AppData\\Local\\atom\\app-1.0.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\emc\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\emc\\.atom\\.apmrc" "install" "C:\\Users\\emc\\AppData\\Local\\Temp\\d-11576-9408-obfyto\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\emc\.atom\.apm\_git-remotes\git-github-com-AtomLinter-csslint-da61e1bd'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by bigbrozer** [comment]
Hi,
Same problem. I'm behind a HTTP proxy, I think the **git://** protocol used by the dependencies is not supported in this case (introduced in commit 4e76b8a6daedcc4e4cb1cd1daf792d37382b0e69).

**Comment by emcek** [comment]
Looks like, I'm behind proxy as well :(

**Comment by forresst** [comment]
This solution in `package.json` could fix the problem? (like https://github.com/atom/scoped-property-store/commit/f80af58fde1d9ae1d137b28dec4b0b0961eaae23)

"csslint": "git***+https***://github.com/AtomLinter/csslint",

**Comment by steelbrain** [comment]
Right.

**Comment by forresst** [comment]
With a new version (1.0.1), works fine ! Thanks

**Comment by bigbrozer** [comment]
Cooool :-) Did not know about this trick ! Thanks.
