### ISSUE TITLE
This should not Lint minified files.

### ISSUE THREAD

**Issue by danielmahon** [AtomLinter/linter-csslint#4]
Upon selecting a minified css file this linter runs and basically breaks Atom, or at least grinds it to a halt. Maybe look for `.min.css` or similar in the filename and skip those files, or look for 1 line files of a certain length?

**Comment by steelbrain** [comment]
it'd be a piece of cake once the upgrade to latest API PR is merged in.

**Comment by Arcanemagus** [comment]
Marking this as closed, this functionality has been generalized in the linter package itself under the "Do Not Lint Files that match this Glob" setting. (And most likely also "Do Not Lint Files Ignored by VCS")
