### ISSUE TITLE
Suppress warnings?

### ISSUE THREAD

**Issue by stela5** [AtomLinter/linter-csslint#44]
Is there a way to suppress warnings and only show errors?
https://github.com/CSSLint/csslint/wiki/Command-line-interface#options

I tried adding the following to *config.cson* without effect:

```
  "linter-csslint": 
    quiet: true
```

```
  "linter-csslint": 
    global: "--quiet"
```

**Comment by Arcanemagus** [comment]
This doesn't run the command line interface, but rather runs `csslint` (the node module) on the code directly. As such the command line options don't mean anything here. Currently this has no configuration options actually, so to accomplish this you would need to ignore warning level errors while generating the messages for `linter`. Somebody would need to submit a PR that accomplishes this.

**Comment by Arcanemagus** [comment]
As `csslint` itself appears to be abandoned I'm marking this as closed. I would _highly_ recommend moving to something like [linter-stylelint](https://github.com/AtomLinter/linter-stylelint).

If somebody feels the urge to write up a PR for this though I'm not opposed to merging it in :wink:.
