### ISSUE TITLE
Not able to install linter-csslint

### ISSUE THREAD

**Issue by lennpet** [AtomLinter/linter-csslint#46]
Installing “linter-csslint@1.0.5” failed.Hide output…

npm WARN addRemoteGit git+https://github.com/AtomLinter/csslint.git resetting remote /Users/lenp/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1 because of error: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! git clone --template=/Users/lenp/.atom/.apm/_git-remotes/_templates --mirror https://github.com/AtomLinter/csslint.git /Users/lenp/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1: Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/lenp/.atom/.apm/.apmrc" "--userconfig" "/Users/lenp/.atom/.apmrc" "install" "/private/var/folders/c4/3vlzys1d6951m5f8315pz7700000gn/T/d-115822-25110-1esnmpi/package.tgz" "--target=0.30.6" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 69

npm ERR! Command failed: 
npm ERR! 
npm ERR! Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/c4/3vlzys1d6951m5f8315pz7700000gn/T/apm-install-dir-115822-25110-6ownw5/npm-debug.log

- and there is no file as specified above.

/L

**Comment by steelbrain** [comment]
The error is
```
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
Do that and try again

**Comment by steelbrain** [comment]
Here's a stackoverflow link http://stackoverflow.com/questions/26197347/agreeing-to-the-xcode-ios-license-requires-admin-privileges-please-re-run-as-r

**Comment by lennpet** [comment]
Nice, thanks.
