### ISSUE TITLE
Add options in settings panel

### ISSUE THREAD

**Issue by rugk** [AtomLinter/linter-csslint#62]
Instead of [saying the user](https://github.com/bsnux/linter-python-pep8#settings) to edit the `config.cson` you should better include these options in the UI of the package settings like other packages does which depend on files installed outside of Atom.

**Comment by Arcanemagus** [comment]
Did you mean to open this issue on the `linter-python-pep8` repository?

This package currently has no settings that can be configured...

**Comment by Arcanemagus** [comment]
Looks like you already did open this over there, so I'm really not sure what your intent was. Please elaborate or open a new issue :wink:.

**Comment by rugk** [comment]
The issue is valid here. I just forgot to replace the link. In fact here the settings are mentioned: https://atom.io/packages/linter-csslint (part #Settings).

This is a setting which can be moved into the UI part of the package's settings panel.

**Comment by Arcanemagus** [comment]
There are _no_ settings for this package, as you can see this has been removed in the [README.md](https://github.com/AtomLinter/linter-csslint/blob/master/README.md), however it looks like apm is using the readme from the last released version which still (erroneously) listed that as an option.

I haven't pushed out a release as there have been no code changes, but I'm thinking of putting the `csslint` code we are using directly in this package to solve the bugs with `apm` failing to checkout the other repo so whenever that gets pushed out the readme on apm should get updated.

**Comment by rugk** [comment]
Okay, but how to you specify the path to csslint if this is installed in a non-standard location?

**Comment by Arcanemagus** [comment]
You can't.

Default versions of `csslint` are broken in ways that make using them for something like this _extremely_ difficult and buggy. `csslint` has had no development work on it for 9 months and looks to be completely abandoned. There have been [some movements](https://github.com/CSSLint/csslint/issues/616) on getting it restarted but nothing has come of them as of yet. We are using a fork that patches in some fixes to get it usable for the purposes of this package but I would highly recommend using a different CSS checker like [linter-stylelint](https://github.com/AtomLinter/linter-stylelint).

I'm a little curious as to why you would want to though as this bundles the latest master branch of `cslint`.

**Comment by rugk** [comment]
> as this bundles the latest master branch of cslint.

Ah CSSLint is already included in the package? I thought it have to be installed manually.

And if you say that csslint is basically dead I'm okay with using another linter. Did not knew that it was abandoned.

**Comment by Arcanemagus** [comment]
This package uses [this fork](https://github.com/AtomLinter/csslint) which is based on the current master. Although I think to remove several issue I'm just going to bring that code into here since many people using semi-broken `git` installs can't check that out.
