### ISSUE TITLE
Writing css on a markdonw file fires the linter

### ISSUE THREAD

**Issue by Bultack** [AtomLinter/linter-csslint#66]
If you're writing a css code in a markdown file, the css linter checks the whole file and throws error in all the lines:

CSSLint Error Unexpected token '#' at line 1, col 1.at line 1 col 1
CSSLint Error Unexpected token '#' at line 3, col 1.at line 3 col 1
CSSLint Error Expected LBRACE at line 3, col 1.at line 3 col 1
CSSLint Warning The universal selector (*) is known to be slow.at line 4 col 1

**Comment by Arcanemagus** [comment]
This is a bug with Atom's [language-gfm](https://github.com/atom/language-gfm/issues/121), I would recommend you switch to [language-markdown](https://atom.io/packages/language-markdown) as it fixes this (among many other things wrong with language-gfm).

Do note that if you are using Markdown Preview you need version v0.157.0 or it won't show up. You can instead install Markdown Preview Plus if you are not on a version of Atom that has that built in.
