### ISSUE TITLE
Installing “linter-csslint@1.1.0” failed.

### ISSUE THREAD

**Issue by akrawitz** [AtomLinter/linter-csslint#68]
I realize there is already an issue about a failed install, but since the error message here is different, I thought it better to file a new issue. It appears that the problem may be with file path handling on Windows. The error seems to be that two versions of the filepath are getting pasted together. Here is the actual error:
```
fatal: '/cygdrive/c/Users/akrawitz/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1/C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1' does not appear to be a git repository
```

When I look at the path "C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1" it looks fine, so I think the problem is the way it is sticking the "/cygdrive/..." version of the path and the "C:\..." version of the path together.

I'm not sure where to begin looking for the problem.

Here is the full output from the error message in Atom:
```
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: Cloning into 'C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893'...
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: fatal: '/cygdrive/c/Users/akrawitz/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1/C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1' does not appear to be a git repository
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: 
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: and the repository exists.
npm ERR! git clone C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1 C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893: 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\akrawitz\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\akrawitz\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\akrawitz\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\akrawitz\\.atom\\.apmrc" "install" "C:\\Users\\akrawitz\\AppData\\Local\\Temp\\d-1151128-3680-iq1h2f\\package.tgz" "--target=0.34.3" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\akrawitz\AppData\Local\Temp\npm-6364-9fa920f9\git-cache-619ca05cb3d2\a976a19ecea490d53c790f15b9e553deabb30893'...
npm ERR! fatal: '/cygdrive/c/Users/akrawitz/.atom/.apm/_git-remotes/https-github-com-AtomLinter-csslint-git-d9ec64d1/C:\Users\akrawitz\.atom\.apm\_git-remotes\https-github-com-AtomLinter-csslint-git-d9ec64d1' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by Arcanemagus** [comment]
That is a new stack trace (Are you running Atom through `cygwin`?), but the issue is the same: The custom fork of `csslint` being used here to get it working at all.

I think with as much problems people are having checking that out we just need to embed it in the repo :frowning:...

**Comment by akrawitz** [comment]
I've resolved the issue. In case it helps someone else, I will describe the problem and solution here:

Problem:
Installing a package in `Atom` uses `apm`, which uses `npm`, which (in this case) uses `git`. `apm` and `npm` are installed as part of the standard `Atom` installation, but `git` is not. I have `GitHub Desktop` installed, but despite the fact that it does install `git`, it does not add it to the `PATH`. I also have `cygwin` installed, which in my case does include a version of `git` that was visible on the `PATH`. So, when I tried to install `linter-csslint` from inside Atom, it was calling my `cygwin` version of `git`, which was causing the path problem I described in this issue.

Solution:
Install `Git for Windows` and tell it to make `git` available from the command line, which means it adds it to your `PATH`. In my case, I also had to edit the `PATH` to move `Git for Windows` before `cygwin` in the `PATH`. I then restarted `Atom` and everything worked fine.

**Comment by Arcanemagus** [comment]
Sorry, should have mentioned the ways to workaround this issue for you @akrawitz, it looks like you figured it out on your own though :wink:

This package should only require Atom on the computer, which is why the current installation process is failing for o many people.
