### ISSUE TITLE
linter-csslint 1.2.0 release leaves spawned child running on Atom Exit

### ISSUE THREAD

**Issue by peterbowey** [AtomLinter/linter-csslint#75]
1) linter-csslint 1.1.0 has no issue on Atom exit (OK).
2) linter-csslint 1.2.0 leaves a spawned child process running at Atom exit (see below) (creates zombie child).

Via #2), the process that remains shows as (via ps faux):

```
root      5337  1.2  0.6 944596 52324 ?        Sl   22:28   0:00  \_ /usr/share/atom/atom --no-deprecation /root/.atom/packages/linter-csslint/node_modules/atomlinter-csslint/cli.js --format=json -
```
The above process adds a new child process on each Atom start and exit.

Thus you end up with a growing collection of child zombies (per atomlinter-csslint/cli.js).

This child process (non-closure) prevents closing (per umount) remote and external drives, as the process (above) prevents a clean exit. Thus, only a manual 'kill xxxx' works to free the child process.

No problem like the above exists with the older ~1.1.0 releases

**Comment by peterbowey** [comment]
This is how the process tree (ps faux) shows when atom is running - with 'linter-csslint 1.2.0) - the first time; using a css file:
```
ps faux | grep -i atom
root      5777  0.0  0.0 119176  1652 ?        S    22:52   0:00  \_ /bin/bash /usr/bin/atom style.css
root      5779  6.6  2.2 1502240 178936 ?      Sl   22:52   0:01      \_ /usr/share/atom/atom --executed-from=/mnt/remote-dp/home/admin/web/computerknowledge.com.au/public_html/wp-content/themes/silence/css --pid=5766 style.css
root      5787  0.1  0.3 466700 29140 ?        S    22:52   0:00          \_ /usr/share/atom/atom --type=zygote --no-sandbox
root      5829 26.3  3.6 1428292 292016 ?      Sl   22:52   0:05              \_ /usr/share/atom/atom --type=renderer --js-flags=--harmony --no-sandbox --lang=en-GB --node-integration=true --enable-delegated-renderer --num-raster-threads=2 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel=5779.0.1966960392 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
root      5869  0.0  0.0 119176  2972 ?        S    22:52   0:00                  \_ /bin/bash /usr/share/atom/resources/app/apm/bin/apm outdated --json --compatible 1.6.1-dev-52c9067 --no-color
root      5906  5.5  0.6 944596 52328 ?        Sl   22:52   0:00                  \_ /usr/share/atom/atom --no-deprecation /root/.atom/packages/linter-csslint/node_modules/atomlinter-csslint/cli.js --format=json -
```

The exit Atom:
```
ps faux | grep -i atom
root      5906  0.4  0.6 944596 52328 ?        Sl   22:52   0:00  \_ /usr/share/atom/atom --no-deprecation /root/.atom/packages/linter-csslint/node_modules/atomlinter-csslint/cli.js --format=json -
```
Start Atom (again) and exit:
```
ps faux | grep -i atom
root      6425  0.0  0.0 118652  1060 pts/0    S+   22:57   0:00  |               \_ grep --color=auto -i atom
root      5906  0.2  0.6 944596 52328 ?        Sl   22:52   0:00  \_ /usr/share/atom/atom --no-deprecation /root/.atom/packages/linter-csslint/node_modules/atomlinter-csslint/cli.js --format=json -
root      6352  0.0  0.0 119176  2984 ?        S    22:57   0:00  \_ /bin/bash /usr/share/atom/resources/app/apm/bin/apm outdated --json --compatible 1.6.1-dev-52c9067 --no-color
root      6393 12.1  0.6 960988 52288 ?        Sl   22:57   0:00  \_ /usr/share/atom/atom --no-deprecation /root/.atom/packages/linter-csslint/node_modules/atomlinter-csslint/cli.js --format=json -
```

**Comment by Arcanemagus** [comment]
That is just bizarre... you only see one process? If it was an issue with how the process is being launched you should see one for every lint request.

Even stranger is that this is being ran exactly how we run all the other node based linters, so I'm inclined to believe this is a bug in csslint itself (which wouldn't be surprising in the slightest).

**Comment by peterbowey** [comment]
@Arcanemagus Yes = bizarre!

In Atom, I use other AtomLinter's; linter-htmlhint, linter-jshint, linter-jsonlint, linter-lua, linter-php, and Linter. All of the above close normally at Atom exit (no left-over process).

For now, I have removed (isolated) linter-csslint to allow clean closure at Atom exit.

Environment: Atom release is 1.6.0 Dev, however the same scenario happens with Atom 1.5.0 Dev (which prompted me to try a new Atom build.

**Comment by Arcanemagus** [comment]
I would recommend you check out `linter-stylelint`, it seems to be a much better CSS linter. Development seems to have have slowly started coming back to life on `csslint` though after a ~10 month hiatus, so we'll see how that goes.

**Comment by peterbowey** [comment]
@Arcanemagus Many thanks, `linter-stylelint` works well! (I did not known it existed for CSS use; probably the key word + search issue).

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed, there is nothing special with how this is launching `csslint` vs. every other program so it must be a bug in `csslint` that is causing this.
