### ISSUE TITLE
Doesn't consider .csslintrc files in parent directories

### ISSUE THREAD

**Issue by MoOx** [AtomLinter/linter-csslint#8]
I don't see anything about the .csslintrc files in the code, not like in jshintrc https://github.com/AtomLinter/linter-jshint/blob/e3e2b7915329c1d3e4f5e7a5fbd6173252580e05/lib/linter-jshint.coffee#L28-L33
Is it planned ?

**Comment by kylewelsby** [comment]
Until this is resolved by the core https://github.com/CSSLint/csslint/issues/529, I would suggest using https://github.com/dmi3y/csslint-cli

    "linter-csslint":
      csslintExecutablePath: "/usr/local/bin/csslint-cli"

**Comment by steelbrain** [comment]
Merging into #29
