### ISSUE TITLE
Remove dependency on custom fork of CSSLint

### ISSUE THREAD

**Issue by sergeychernyshev** [AtomLinter/linter-csslint#91]
Looks like this package depends on a custom fork of CSSLint (https://www.npmjs.com/package/atomlinter-csslint / https://github.com/AtomLinter/csslint).

This does not allow for getting newer versions of CSSLint coming from https://github.com/CSSLint/csslint

I contributed to core project - [documentation URLs](https://github.com/CSSLint/csslint/commit/ba7c0eea2d20ed89f05f92e703b54097de7601d4) to all the rules and looked to surface them in Atom linter so developers can click right from message bubbles and open detailed documentation in the browser .

**Comment by Arcanemagus** [comment]
It would be absolutely amazing to be able to use the main project (especially now that development is (_slowly_) moving again on it), but as you guess from filing https://github.com/CSSLint/csslint/pull/642 (and missing https://github.com/CSSLint/csslint/pull/606 :stuck_out_tongue:) `csslint` isn't at a state where this can be done yet.

Btw, we also need https://github.com/CSSLint/csslint/pull/605 to be merged in before we can switch back to the main repo.

**Comment by Arcanemagus** [comment]
Btw, are you interested in becoming a maintainer of this project? I do what I can when I have time here, but there is currently no dedicated maintainer.

**Comment by sergeychernyshev** [comment]
@Arcanemagus can't go as far as becoming a full maintainer - have my small itch to scratch at the moment and will give it some time though.

**Comment by sergeychernyshev** [comment]
I see that there are a bunch of changes in the fork - is JSON formatter the only dependency?

**Comment by Arcanemagus** [comment]
JSON formatter and `stdin` support, as mentioned.

**Comment by sergeychernyshev** [comment]
Sorry, I missed the point that #605 is for `stdin` support.

**Comment by Arcanemagus** [comment]
The alternative approach would be to use the XML formatter, and move back to disabling `lintOnFly` and only linting on save. I personally don't want anything to do with that though, so...

**Comment by sergeychernyshev** [comment]
I wouldn't want to limit the functionality - liked how it works right now pretty much.

**Comment by Arcanemagus** [comment]
v1.0.0 is out, anyone interested in updating this to that?

**Comment by Arcanemagus** [comment]
#170 moves to utilizing the mainline CSSLint... and disables the ability to lint on changes in the file as CSSLint _still_ doesn't support `stdin` input 2 years later.

As (understandably) nobody is interested in maintaining the `csslint` fork here, this is the only option that allows users to have an up to date version of CSSLint.
