### ISSUE TITLE
Error Process Execution Timed Out

### ISSUE THREAD

**Issue by Deviad** [AtomLinter/linter-csslint#95]
Hello,
I am experiencing this issue when opening a CSS file.
```
Error: Process execution timed out
    at C:\Users\spotted\\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:79:18
```

Link to screenshot: http://imgur.com/CVudlsK
Thank you.
Regards,
Davide

**Comment by Deviad** [comment]
Tried fixing by replacing
`let exec = exports.exec = function () {
  var ref = _asyncToGenerator(function* (command, args, opts, isNode) {
    const options = assign({
      env: yield _consistentEnv2.default.async(),
      stream: 'stdout',
      throwOnStdErr: true,
**      timeout: 10000 // Ten seconds in ms
**    }, opts);
    let timeout;`

with 

let exec = exports.exec = function () {
  var ref = _asyncToGenerator(function* (command, args, opts, isNode) {
    const options = assign({
      env: yield _consistentEnv2.default.async(),
      stream: 'stdout',
      throwOnStdErr: true,
**      timeout: 30000 // Ten seconds in ms
**    }, opts);
    let timeout;

but it did not work

**Comment by Arcanemagus** [comment]
That looks like the generated code inside the `lib` folder of `atom-linter`, the proper way to specify the time would be to add `,timeout: 30000` to the options [here](https://github.com/AtomLinter/linter-csslint/blob/v1.3.2/lib/main.coffee#L26).

That being said, what you did should have worked. Also, do you mind sharing the file or running `time csslint foo.css`? It's quite odd that you should be hitting this.

**Comment by Deviad** [comment]
https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options

Therefore main.coffee now is:
''helpers = null
path = null

module.exports =
  activate: ->
    require('atom-package-deps').install('linter-csslint')

  provideLinter: ->
    provider =
      name: 'CSSLint'
      grammarScopes: ['source.css', 'source.html']
      scope: 'file'
      lintOnFly: true
      lint: (textEditor) ->
        helpers ?= require('atom-linter')
        path ?= require('path')
        filePath = textEditor.getPath()
        timeout = 30000;
        text = textEditor.getText()
        return Promise.resolve([]) if text.length is 0
        parameters = ['--format=json', '-']
        exec = path.join(__dirname, '..', 'node_modules', 'atomlinter-csslint', 'cli.js')
        paths = atom.project.relativizePath(filePath)
        cwd = paths[0]
        if not (cwd)
          cwd = path.dirname(textEditor.getPath())
        helpers.execNode(exec, parameters, {stdin: text, cwd: cwd, timeout}).then (output) ->
          lintResult = JSON.parse(output)
          toReturn = []
          if lintResult.messages.length < 1
            return toReturn
          for data in lintResult.messages
            msg = {}
            if not (data.line and data.col)
              # Use the file start if location not defined
              msg.range = helpers.rangeFromLineNumber(textEditor, 0)
            else
              line = data.line - 1
              col = data.col - 1
              msg.range = [[line, col], [line, col]]
            msg.type = data.type.charAt(0).toUpperCase() + data.type.slice(1)
            msg.text = data.message
            msg.filePath = filePath
            if data.rule.id and data.rule.desc
              msg.trace = [{
                type: "Trace",
                text: '[' + data.rule.id + '] ' + data.rule.desc
              }]
            toReturn.push(msg)
          return toReturn
''

**Comment by thejohnsmith** [comment]
I'm seeing the same issue after the last update, 1.3.2
I'm running Atom 1.5.4, OS X Yosemite 10.10.5

**Comment by jraisanen** [comment]
Same issue here on Atom 1.6.0, works fine for files with line count less than ~3000, anything above that causes the timeout.

**Comment by Arcanemagus** [comment]
Added an option to disable the timeout, can somebody that is having this issue try out the current `master` branch and see if it is working for them?
